#!/usr/bin/env bash
# tests/onboard_rules_spec.sh — Black-Box-Spec für Baustein 8 (.claude/rules-Generierung) in bin/onboard.
#
# Spec-Quelle: team-rules/tag-paths.map (tag→Globs) + team-rules/tags/<tag>.md → bin/onboard
# generiert pro Instanz .claude/rules/<tag>.md mit paths:-Frontmatter (lazy-load, Engine-Diät #34):
#   - je gemapptem Tag eine Regel mit korrektem paths:-Frontmatter + Tag-Inhalt + generated-Marker.
#   - idempotent (2. Lauf → keine Änderung).
#   - projekt-eigene Rules (ohne generated-Marker) bleiben unangetastet.
. "$(dirname "${BASH_SOURCE[0]}")/_helper.sh"

ENGINE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ONBOARD="$ENGINE/bin/onboard"

echo "onboard_rules_spec:"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
# onboard seiteneffekt-frei: eigene temp-Registry, PROJECT_UID gesetzt (kein Prompt), Output verworfen.
onboard_into() { DEV_TEAM_REGISTRY="$TMP/reg.json" PROJECT_UID=acme bash "$ONBOARD" "$1" >/dev/null 2>&1 || true; }

# --- Generierung: backend.md korrekt ---
P1="$TMP/p1"; mkdir -p "$P1"; onboard_into "$P1"
RULE="$P1/.claude/rules/backend.md"
it "backend.md generiert";                       ok test -f "$RULE"
BODY="$(cat "$RULE" 2>/dev/null)"
it "backend.md hat paths:-Frontmatter";          contains "$BODY" "paths:"
it "backend.md trägt Tag-Glob aus der Map";      contains "$BODY" '**/*.rb'
it "backend.md hat generated-Marker";            contains "$BODY" "generated by bin/onboard"
it "backend.md enthält den Tag-Inhalt";          contains "$BODY" "tag: backend"
it "frontend.md ebenfalls generiert";            ok test -f "$P1/.claude/rules/frontend.md"
it "tests.md ebenfalls generiert";               ok test -f "$P1/.claude/rules/tests.md"

# --- Cross-cutting Tag OHNE Pfad-Mapping wird NICHT generiert (review = nicht in der Map) ---
it "review.md NICHT generiert (cross-cutting)";  not_contains "$(ls "$P1/.claude/rules/" 2>/dev/null)" "review.md"

# --- Idempotenz: 2. Lauf ändert backend.md nicht ---
onboard_into "$P1"
it "idempotent: backend.md unverändert";         eq "$BODY" "$(cat "$RULE" 2>/dev/null)"

# --- Non-destruktiv: projekt-eigene Rule (ohne Marker) bleibt erhalten ---
P2="$TMP/p2"; mkdir -p "$P2/.claude/rules"
printf 'eigene projekt-regel ohne marker\n' > "$P2/.claude/rules/backend.md"
onboard_into "$P2"
it "projekt-eigene Rule (kein Marker) unangetastet"; eq "eigene projekt-regel ohne marker" "$(cat "$P2/.claude/rules/backend.md" 2>/dev/null)"

# --- Regression: Map-Globs dürfen NICHT der CWD-Pathname-Expansion zum Opfer fallen ---
# Ohne `set -f` würde `**/*.ts` (=*/*.ts ohne globstar) gegen Dateien im CWD expandiert → konkreter
# Dateiname statt Muster im Frontmatter. onboard daher aus einem CWD MIT passenden Dateien laufen lassen.
CWD_TRAP="$TMP/cwd-with-matches"; mkdir -p "$CWD_TRAP/sub"
: > "$CWD_TRAP/sub/x.ts"; : > "$CWD_TRAP/sub/y.rb"
P3="$TMP/p3"; mkdir -p "$P3"
( cd "$CWD_TRAP" && DEV_TEAM_REGISTRY="$TMP/reg3.json" PROJECT_UID=acme bash "$ONBOARD" "$P3" >/dev/null 2>&1 ) || true
it "js-Glob bleibt literal trotz Match im CWD (**/*.ts)";      contains "$(cat "$P3/.claude/rules/js.md" 2>/dev/null)" '**/*.ts'
it "backend-Glob bleibt literal trotz Match im CWD (**/*.rb)"; contains "$(cat "$P3/.claude/rules/backend.md" 2>/dev/null)" '**/*.rb'
